### ISSUE TITLE
Namespaces missing

### ISSUE THREAD

**Issue by shivamdixit** [gengo/gengo-php#28]
There are no namespaces present in any of the class which is a great drawback for the frameworks which use PSR standards for autoloading.

Wouldn't it be great to have PSR compliant namespaces in the project?

**Comment by hayate** [comment]
thank you @shivamdixit you raise a very good. This library was originally created before the popularity of namespaces in php.
It is definitely something to keep in mind in the potential next version of the library.

**Comment by dusterio** [comment]
I gotta agree – it's nearly impossible to use this package in a modern, convenient way

Would be nice to rely on composer for dependancies and to use namespaces

Also, documentation is non-existent :)

**Comment by Sopamo** [comment]
+1 for namespaces and proper composer setup

**Comment by shivamdixit** [comment]
I might work on this next weekend if I get time

**Comment by hayate** [comment]
@shivamdixit @dusterio @Sopamo closing this issue as fixed from version 3.0 thanks to @vbashkirtsev
