### ISSUE TITLE
Replace Zend with Requests

### ISSUE THREAD

**Issue by hayate** [gengo/gengo-php#31]
As the `Zend` library is primarily used to make HTTP requests it would be beneficial for `gengo-php` code base to use [Requests](https://github.com/rmccue/Requests "Requests") which is a more lightweight but equally powerful library to make HTTP requests.

**Comment by robmcvey** [comment]
:-1:

**Comment by hayate** [comment]
@robmcvey feedback more than welcome, could you elaborate a bit more?

**Comment by robmcvey** [comment]
Would not be in favour of simply replacing a library with another library. 

It might be a good time to look at PSR-4.0 (see #28) and using composer to manage such dependencies? 

Maybe something to consider if a `gengo-php version 3.0` is in the pipeline.

Would be more than happy to contribute :smiley:

**Comment by hayate** [comment]
thanks @robmcvey as mentioned on the issue #28 that you reference I am totally in agreement.
Time and priorities is the only constraint at the moment.
Contribution as super welcome, so thank you, I will definitely give you a heads-up should we start the new version.

**Comment by hayate** [comment]
@robmcvey this issue is resolved in version 3.0 thanks to @vbashkirtsev
