### ISSUE TITLE
autoload statement missing from composer.json

### ISSUE THREAD

**Issue by vbashkirtsev** [gengo/gengo-php#38]
Plain mention in require section of gengo/gengo does not help much to load the classes on demand. Package's composer.json missing the following statement:

"autoload": {
 "classmap": ["libs/Gengo", "libs/Gengo/Api"]
}

Without it call to Gengo_Api fails with class not found error.

Of course PSR-4 would be better if this package would use namespaces.

**Comment by hayate** [comment]
Thank you for the report @vbashkirtsev 
Please note the following:
1. This library is public and open source which means that PR are more than welcome
2. This library is rather old, when the first version was written Namespace did not exist in PHP let alone composer
3. If you look at the example folder you will notice that `init.php` is required. When that file is required an autoloader is initialized which fixes the class not found error.

I would love PSR-4 compliance on this library too, but I don't have the bandwidth at the moment.

**Comment by vbashkirtsev** [comment]
If I refactor this library to use namespaces and comply with PSR-4 (therefore pushing it to 3.0.0) will you accept such PR? I see that your own PR still pending for a year.

**Comment by hayate** [comment]
@vbashkirtsev if it LGTM and the code works there is not reason for not accepting.

It turns out my own PR was not that required, nevertheless will merge it now, thank you.

**Comment by vbashkirtsev** [comment]
OK. Will get it done and will let you know when ready.

**Comment by vbashkirtsev** [comment]
You've got new PR :) I guess at this point you should close out all outstanding issues as they all were addressed.

**Comment by vbashkirtsev** [comment]
I am closing this issue as it was fixed. @hayate: I believe you should close other three issues as they are done too.

**Comment by hayate** [comment]
will do, thank you @vbashkirtsev
