### ISSUE TITLE
Error downloading logics/sql

### ISSUE THREAD

**Issue by ryanannatuvasquez** [gengo/gengo-php#46]
@vbashkirtsev i think you're SSL certificate expired. We can't download the package.

## Screenshot
<img width="1121" alt="screen shot 2016-12-06 at 5 34 27 pm" src="https://cloud.githubusercontent.com/assets/8102493/20920376/b17d3c98-bbda-11e6-991e-e0e73fbdbf2c.png">

**Comment by evgeny-l** [comment]
+1
```
Updating dependencies (including require-dev)
  - Installing logics/sql (0.1)
    Checking out /tags/0.1/@48


  [RuntimeException]
  Package could not be downloaded,
  sh: 1: svn: not found
```

**Comment by vbashkirtsev** [comment]
@ryanannatuvasquez:

```
[mega@dev gengo]$ openssl s_client -connect open.logics.net.au:443 | openssl x509 -noout -dates
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = open.logics.net.au
verify return:1
notBefore=Nov 15 12:07:00 2016 GMT
notAfter=Feb 13 12:07:00 2017 GMT

```

Clearly there no issue with expiration date on our certificate. I suggest you to update your root certificates. Please see https://letsencrypt.org/certificates/ for additional information.

**Comment by vbashkirtsev** [comment]
@evgeny-l: The message you've got says 'svn: not found'. That's exactly what your issue is: you don't have Subversion installed on YOUR system.

**Comment by evgeny-l** [comment]
@vbashkirtsev Yep, already got it, missed that point. Anyway, dependency from SVN for single composer package is too much. Decided not to use that. Thanks.

**Comment by vbashkirtsev** [comment]
@evgeny-l : we working on getting our svn repositories to github

**Comment by ryanannatuvasquez** [comment]
I solved the problem my connecting to the SVN repo once and accept the cert manually, then composer worked again.
